version: 0.2

phases:
  build:
    commands:
      - echo Build phase started on `date`
      - echo Image already exists on DockerHub
      - docker pull iniyacloud03/brain-tasks-app:1.0
      - printf '[{"name":"brain-tasks-app","imageUri":"iniyacloud03/brain-tasks-app:1.0"}]' > imagedefinitions.json

  post_build:
    commands:
      - echo Build phase completed on `date`
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - k8s/deployment.yaml
    - k8s/service.yaml
