version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t iniyacloud03/brain-tasks-app:latest .
      - docker tag iniyacloud03/brain-tasks-app:latest iniyacloud03/brain-tasks-app:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push iniyacloud03/brain-tasks-app:latest
      - docker push iniyacloud03/brain-tasks-app:$CODEBUILD_BUILD_NUMBER
      - echo Writing image definitions file...
      - printf '[{"name":"brain-tasks-app","imageUri":"%s"}]' iniyacloud03/brain-tasks-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - k8s/deployment.yaml
    - k8s/service.yaml
